image: docker:dind

variables:
  PROJECT: 'agents-mulesoft'

  # Fortify
  FORTIFY_PROJECT: "10715"
  FORTIFY_BUILD_ID: "agents-mulesoft"

  # Whitesource
  WS_PROJECT_ID: "agents-mulesoft"
  WS_CONFIG_FILE: "whitesource.config"
  WS_BRANCH: main

include:
  - project: "apigov/beano_cicd"
    ref: master
    # the order of these include files is important
    file:
      - "/gitlabci/csrjobs.yml"
  - project: 'scurity/gitlabci'
    ref: master
    file:
      - '/.gitlab-ci-prepcsr.yml'
      - '/.gitlab-ci-fortify.yml'
      - "/.gitlab-ci-whitesource.yml"
      - "/.gitlab-ci-twistlock.yml"
      - "/.gitlab-ci-csr.yml"

stages:
  # - build
  # - push
  - security-scans
  - security-review

.add-ca-cert: &add-ca-cert |
  curl -s http://swf-artifactory.lab.phx.axway.int/artifactory/certs/Axway-CA.crt -o Axway-CA-new.crt
  mv Axway-CA-new.crt /usr/local/share/ca-certificates/
  update-ca-certificates

.go-setup: &go-setup |
  # Ensure the project is under the go path
  cd $GOPATH/src
  # attempt to install golint before cd'ing to project dir so no other deps are updated
  go get -x golang.org/x/lint/golint
  # show where it got installed
  go list -f {{.Target}} golang.org/x/lint/golint
  # Create path to the project. Should match location of repo (needed for imports)
  mkdir -p git.ecd.axway.org/$CI_PROJECT_NAMESPACE
  # cd into project directory
  cd git.ecd.axway.org/$CI_PROJECT_NAMESPACE
  # Link the project with the current directory
  ln -s $CI_PROJECT_DIR
  # cd into project
  cd $CI_PROJECT_NAME
  pwd

####################
# CSR - overridden from csrjobs.yml to effectively not see this job ever
####################
.dummy:
  stage: security-scans
  only:
    - xxxxx
  script:
    - ""

fetch-iriusrisk:
  extends: .dummy

whitesource:
  before_script:
    - echo "before wssched $CI_COMMIT_REF_NAME"
    - echo "$WS_PROJECT_ID"
    - echo "$WS_CONFIG_FILE"

whitesource:on-schedule:
  before_script:
    - echo "before wssched $CI_COMMIT_REF_NAME"

run-csr:
  dependencies:
    - fetch-fortify
    - whitesource

update-csr:
  dependencies:
    - fetch-fortify
    - whitesource:on-schedule
