image: docker:dind

variables:
  PROJECT: 'agents-mulesoft'
  CSR_SUPPRESSION_LIST: "/tmp/csr-suppressions/amplify-central/golang-agents-common.json"

  # Fortify
  FORTIFY_PROJECT: "10715"
  FORTIFY_BUILD_ID: "agents-mulesoft"

  # Whitesource
  WS_PROJECT_ID: "agents-mulesoft"
  WS_CONFIG_FILE: "whitesource.config"
  WS_BRANCH: main

  KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD+ALCNR0YXwJKdcCN9zSMtdLVDTnhck7oXFk7b4LwXMyz36HTbaS2OOejafnjzcW2UBhSfyZ6BVCAWBamRgXge6bj4muYbVwPEljm786B/+VGwcaPT3yiIa5gymkSWALqBRPV0OssZwdYaAmqOEek6XlBu8iriK2xq5FqJiJCR2HFzy1rh3bW2vK3N6mLs3VJFUAzXh0JUldO3VagJArgEoOECgqGTwQKgAehQ3Bgioi3gOqVy1uVEMhDmpfDj29Bs+msv3tP0Eh1JjNsdp997GTEKUGFuTJpxaukp7iwTrzLyfLIu23d8MRKTWZDNtbtOtn2ahHNew4X8IMXTr5xy7z4g9pkI1rl9K70RkqMyf6rSOiZI9uz64ShLPtwvoxt3JyD3HKGhV6Qy1iP2T/ioLvZCkykylM/bb1Th7UaLRyLfQ3SEGwlqHU+WVKTb3HbWmisd5RGML5j1nIE96uHfoaWFh4qcCRxja3rLFspKtnCg+z7Iv1+uDBmsS0W8ilc28a5tKRvVZ7tNQNjF4Ie10nd/II99+cuzdLL7nbLE6AJbWcCORBWStps6DZmwFfixIoEJI4Yhpg/eAnTv9VQTeKIGZ8v8wSi3PddpkA5v2Am27YsoU6OfjAMTOWdsX62RyKj57chK8PlxpQgpREMoDMJrcI5h+ip22CITMj+3wQ== git@git.ecd.axway.org"

include:
  - project: "apigov/beano_cicd"
    ref: master
    # the order of these include files is important
    file:
      - "/gitlabci/csrjobs.yml"
  - project: 'scurity/gitlabci'
    ref: master
    file:
      - '/.gitlab-ci-prepcsr.yml'
      - '/.gitlab-ci-fortify.yml'
      - "/.gitlab-ci-twistlock.yml"
      - "/.gitlab-ci-whitesource.yml"
      - "/.gitlab-ci-csr.yml"

stages:
  # - build
  # - push
  - security-scans
  - security-review

####################
# CSR - overridden from csrjobs.yml to effectively not see this job ever
####################
.dummy:
  stage: security-scans
  only:
    refs:
      - xxxxx
  script:
    - ""

fetch-iriusrisk:
  extends: .dummy

# twistlock:
#   extends: .dummy

# twistlock:on-schedule:
#   extends: .dummy
#    - docker login ghcr.io --username dfeldick sh-rsa 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
twistlock:
  before_script:
    - export IMAGE_NAME=ghrc.io/axway/apigee_discovery_agent:v0.0.6
    - docker login ghcr.io --username dfeldick --password 76405axManO4
    - docker pull ${IMAGE_NAME}

twistlock:on-schedule:
  before_script:
    - export IMAGE_NAME=ghrc.io/axway/apigee_discovery_agent:v0.0.6
    - docker login ghcr.io --username dfeldick sh-rsa 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
    - docker pull ${IMAGE_NAME}

twistlock-master:
  extends: .dummy

run-csr:
  dependencies:
    - fetch-fortify
    - whitesource

update-csr:
  dependencies:
    - fetch-fortify
    - whitesource:on-schedule
