image: docker:dind

variables:
  PROJECT: 'agents-mulesoft'
  CSR_SUPPRESSION_LIST: "/tmp/csr-suppressions/amplify-central/golang-agents-common.json"

  # Fortify
  FORTIFY_PROJECT: "10715"
  FORTIFY_BUILD_ID: "agents-mulesoft"

  # Whitesource
  WS_PROJECT_ID: "agents-mulesoft"
  WS_CONFIG_FILE: "whitesource.config"
  WS_BRANCH: main

  KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD+ALCNR0YXwJKdcCN9zSMtdLVDTnhck7oXFk7b4LwXMyz36HTbaS2OOejafnjzcW2UBhSfyZ6BVCAWBamRgXge6bj4muYbVwPEljm786B/+VGwcaPT3yiIa5gymkSWALqBRPV0OssZwdYaAmqOEek6XlBu8iriK2xq5FqJiJCR2HFzy1rh3bW2vK3N6mLs3VJFUAzXh0JUldO3VagJArgEoOECgqGTwQKgAehQ3Bgioi3gOqVy1uVEMhDmpfDj29Bs+msv3tP0Eh1JjNsdp997GTEKUGFuTJpxaukp7iwTrzLyfLIu23d8MRKTWZDNtbtOtn2ahHNew4X8IMXTr5xy7z4g9pkI1rl9K70RkqMyf6rSOiZI9uz64ShLPtwvoxt3JyD3HKGhV6Qy1iP2T/ioLvZCkykylM/bb1Th7UaLRyLfQ3SEGwlqHU+WVKTb3HbWmisd5RGML5j1nIE96uHfoaWFh4qcCRxja3rLFspKtnCg+z7Iv1+uDBmsS0W8ilc28a5tKRvVZ7tNQNjF4Ie10nd/II99+cuzdLL7nbLE6AJbWcCORBWStps6DZmwFfixIoEJI4Yhpg/eAnTv9VQTeKIGZ8v8wSi3PddpkA5v2Am27YsoU6OfjAMTOWdsX62RyKj57chK8PlxpQgpREMoDMJrcI5h+ip22CITMj+3wQ== git@git.ecd.axway.org"

include:
  - project: "apigov/beano_cicd"
    ref: master
    # the order of these include files is important
    file:
      - "/gitlabci/csrjobs.yml"
  - project: 'scurity/gitlabci'
    ref: master
    file:
      - '/.gitlab-ci-prepcsr.yml'
      - '/.gitlab-ci-fortify.yml'
      - "/.gitlab-ci-twistlock.yml"
      - "/.gitlab-ci-whitesource.yml"
      - "/.gitlab-ci-csr.yml"

stages:
  # - build
  # - push
  - security-scans
  - security-review

####################
# CSR - overridden from csrjobs.yml to effectively not see this job ever
####################
.dummy:
  stage: security-scans
  only:
    refs:
      - xxxxx
  script:
    - ""

fetch-iriusrisk:
  extends: .dummy

# twistlock:
#   extends: .dummy

# twistlock:on-schedule:
#   extends: .dummy
twistlock:
  before_script:
    - export IMAGE_NAME=ghrc.io/axway/apigee_discovery_agent:v0.0.6
    - docker login ghcr.io --username dfeldick sh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/nWB9HeHLh1tC/k0zTPjMTw1cmTrLNLqXBqIqM7ioiw3i+Cpanidh6tvq6B30InDSwb+R8MNUOYqjvhMUoV/zqplMnWRCUmqDJrfLRmHH8drmpzBXRjx9hOFSlHwk83oPj5LBJPhzzAnhs5C/uEBJ0WfSkict9u3rL1cxFDQSlqVymV1+XLrJ4BXDmI6DB6J3C+D/nbzCn99r2wbiWwIQ3KOPX3PjPx7+WEF2yZv8V8+CToMUbSAKkS2FyXZlULnY5bAgqom+xI0xNGz6F79jGbw5lJVPLgOjDx0R6RKS/1NOMLO2H7Z769/fVBp5Vc1pcltTa+ysQzpCf+cvG3EhEAwKvp4ni8mgq6JfumlVXIa+KxFiZ+F31bygbHCKIdFD29sfeXqvDDsccBNTy1zAvNPvAQHdOObkiqSNTw9/+YwJOiEUXFeApirTWD4zgX8SgBVe9BI7n959MD2NC69D/ffCjy6wZI9oPIpaNArlZ/w10gGh53BsjJfGyJMlsDpMv9bXXJr+p+FS4vmxg136C7lQy/vObbU1RFlKK9MY7mx0cY9BKLzYbg3o0GBLDP45jOtZi9wYXqwMhWkTcmxhM8JKHTW6daaAz2VSZTMvSxu8bhwB7JWjVwmSxAKPpyGYsZxysAEGhPp5Cc9GRAe5FewYCW52vpnZRbacr21EJQ== dfeldick@axway.com
    - docker pull ${IMAGE_NAME}

twistlock:on-schedule:
  before_script:
    - export IMAGE_NAME=ghrc.io/axway/apigee_discovery_agent:v0.0.6
    - docker login ghcr.io --username dfeldick sh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/nWB9HeHLh1tC/k0zTPjMTw1cmTrLNLqXBqIqM7ioiw3i+Cpanidh6tvq6B30InDSwb+R8MNUOYqjvhMUoV/zqplMnWRCUmqDJrfLRmHH8drmpzBXRjx9hOFSlHwk83oPj5LBJPhzzAnhs5C/uEBJ0WfSkict9u3rL1cxFDQSlqVymV1+XLrJ4BXDmI6DB6J3C+D/nbzCn99r2wbiWwIQ3KOPX3PjPx7+WEF2yZv8V8+CToMUbSAKkS2FyXZlULnY5bAgqom+xI0xNGz6F79jGbw5lJVPLgOjDx0R6RKS/1NOMLO2H7Z769/fVBp5Vc1pcltTa+ysQzpCf+cvG3EhEAwKvp4ni8mgq6JfumlVXIa+KxFiZ+F31bygbHCKIdFD29sfeXqvDDsccBNTy1zAvNPvAQHdOObkiqSNTw9/+YwJOiEUXFeApirTWD4zgX8SgBVe9BI7n959MD2NC69D/ffCjy6wZI9oPIpaNArlZ/w10gGh53BsjJfGyJMlsDpMv9bXXJr+p+FS4vmxg136C7lQy/vObbU1RFlKK9MY7mx0cY9BKLzYbg3o0GBLDP45jOtZi9wYXqwMhWkTcmxhM8JKHTW6daaAz2VSZTMvSxu8bhwB7JWjVwmSxAKPpyGYsZxysAEGhPp5Cc9GRAe5FewYCW52vpnZRbacr21EJQ== dfeldick@axway.com
    - docker pull ${IMAGE_NAME}

twistlock-master:
  extends: .dummy

run-csr:
  dependencies:
    - fetch-fortify
    - whitesource

update-csr:
  dependencies:
    - fetch-fortify
    - whitesource:on-schedule
