# Documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - id: mulesoft_discovery_agent
    binary: mulesoft_discovery_agent
    main: ./cmd/discovery/main.go
    flags:
      - -tags=static_all
      - -a
    ldflags:
      - -X 'github.com/Axway/agent-sdk/pkg/cmd.BuildTime={{ .Date }}'
      - -X 'github.com/Axway/agent-sdk/pkg/cmd.BuildVersion={{ .Version }}'
      - -X 'github.com/Axway/agent-sdk/pkg/cmd.BuildCommitSha={{ .Commit }}'
      - -X 'github.com/Axway/agent-sdk/pkg/cmd.BuildAgentName=MuleSoftDiscoveryAgent'
      - -X 'github.com/Axway/agent-sdk/pkg/cmd.BuildAgentDescription=MuleSoft Discovery Agent'
      - -X 'github.com/Axway/agent-sdk/pkg/cmd.SDKBuildVersion={{ .Env.SDK_VERSION }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: discovery_agent_archives
    name_template: >-
      mulesoft_discovery_agent_
      {{ .Version }}_
      {{ .Os }}_
      {{- if eq .Arch "darwin" }}Darwin
      {{- else if if eq .Arch "linux" }}Linux
      {{- else if eq .Arch "windows" }}Windows
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .ARCH }}{{ end }}
    wrap_in_directory: discovery_agent
    files:
      - README_discovery.md
      - README_subscription.md
      - src: build/mulesoft_discovery_agent.yml
        dst: .
        strip_parent: true

checksum:
  name_template: "discovery_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
