# Documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go mod tidy
    - go mod vendor
# - export sdkVersion=`go list -m github.com/Axway/agent-sdk | awk '{print $$2}' | awk -F'-' '{print substr($$1, 2)}'`

builds:
  - id: mulesoft_traceability_agent
    binary: mulesoft_traceability_agent
    main: ./cmd/traceability/main.go
    flags:
      - -tags=static_all
      - -a
    ldflags:
      - -X 'github.com/Axway/agent-sdk/pkg/cmd.BuildTime={{.Date}}'
      - -X 'github.com/Axway/agent-sdk/pkg/cmd.BuildVersion={{.Version}}'
      - -X 'github.com/Axway/agent-sdk/pkg/cmd.BuildCommitSha={{.Commit}}'
      - -X 'github.com/Axway/agent-sdk/pkg/cmd.BuildAgentName=MulesoftTraceabilityAgent'
      - -X 'github.com/Axway/agent-sdk/pkg/cmd.BuildAgentDescription=Mulesoft Traceability Agent'
      - -X 'github.com/Axway/agent-sdk/pkg/cmd.BuildDataPlaneType=Mulesoft'
    env:
      - CGO_ENABLED=0
    goos:
      # - linux
      - windows
      # - darwin

archives:
  - id: traceability_agent_archives
    name_template: "mulesoft_traceability_agent_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    wrap_in_directory: traceability_agent
    files:
      - mulesoft_traceability_agent.yml
      - README_traceability.md

checksum:
  name_template: "traceability_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
