apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-agent
  labels:
    name: discovery-agent
    instance: discovery
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: discovery-agent
      app.kubernetes.io/instance: discovery
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: discovery-agent
        app.kubernetes.io/instance: discovery
    spec:
#      imagePullSecrets:
#        - name: <Secret_Name>
      containers:
        - env:
            - name: CENTRAL_AUTH_CLIENTID
              value: DOSA_c544a7c1a52348139da6277a33239772
            - name: CENTRAL_AUTH_PRIVATEKEY
              value: /keys/privateKey
            - name: CENTRAL_AUTH_PUBLICKEY
              value: /keys/publicKey
            - name: CENTRAL_POLLINTERVAL
              value: 20s
            - name: CENTRAL_ENVIRONMENT
              value: demo
            - name: CENTRAL_TEAM
              value: "Default Team"
            - name: CENTRAL_ORGANIZATIONID
              value: "383015860672618"
            - name: LOG_LEVEL
              value: debug
            - name: LOG_OUTPUT
              value: stdout
            - name: LOG_PATH
              value: logs
            - name: MULESOFT_ANYPOINTEXCHANGEURL
              value: https://anypoint.mulesoft.com
            - name: MULESOFT_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: muleauth-discovery
                  key: password
            - name: MULESOFT_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: muleauth-discovery
                  key: username
            - name: MULESOFT_CACHEPATH
              value: /tmp
            - name: MULESOFT_ENVIRONMENT
              value:
            - name: MULESOFT_ORGNAME
              value:
            - name: MULESOFT_POLLINTERVAL
              value: 20s
            - name: STATUS_PORT
              value: "8989"
          image: <Path_To_Image>
          imagePullPolicy: Always
          name: discovery
          resources: {}
          volumeMounts:
            - mountPath: /keys
              name: jwt-auth-keys-volume
      restartPolicy: Always
      volumes:
        - name: jwt-auth-keys-volume
          secret:
            secretName: key-pair