# Build image
FROM golang:1.13 as builder
ENV APP_HOME /go/src/github.com/Axway/agents-mulesoft
ENV APP_USER axway

RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME


# Copy necessary files
COPY . . 

RUN make download
RUN make verify
RUN make build-trace

USER $APP_USER

FROM alpine:3.12.3
ENV APP_HOME /go/src/github.com/Axway/agents-mulesoft
ENV APP_USER axway

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /etc/passwd /etc/passwd   
COPY --from=builder $APP_HOME/default_mulesoft_traceability_agent.yml /mulesoft_traceability_agent.yml
COPY --from=builder $APP_HOME/bin/traceability /traceability

RUN mkdir /keys && \
  chown -R $APP_USER /keys \
  apk add ca-certificates && apk update && update-ca-certificates \
  apk --no-cache add curl=7.69.1-r0 \ 
  find / -perm /6000 -type f -exec chmod a-s {} \; || true

USER $APP_USER

VOLUME ["/keys"]

HEALTHCHECK --retries=1 CMD curl --fail http://localhost:${STATUS_PORT:-8989}/status || exit 1

ENTRYPOINT ["/traceability"]
