# Documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - go mod tidy
    - go mod vendor
    - go get "github.com/Axway/agent-sdk@main"
builds:
  - id: mulesoft_discovery_agent
    binary: bin/mulesoft_discovery_agent
    main: ./main.go
    flags:
      - -tags=static_all
      - -a
    ldflags:
      - -X 'github.com/Axway/agent-sdk/pkg/cmd.BuildTime={{.Date}}'
      - -X 'github.com/Axway/agent-sdk/pkg/cmd.BuildVersion={{.Version}}'
      - -X 'github.com/Axway/agent-sdk/pkg/cmd.BuildCommitSha={{.Commit}}'
      - -X 'github.com/Axway/agent-sdk/pkg/cmd.BuildAgentName=MulesoftDiscoveryAgent'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "discovery_checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
