name: Mulesoft Traceability Agent Docker
on:
  push:
    tags:
      - xxx

jobs:
  build:
    env:
      GOFLAGS: "-mod=mod"
      IMAGE_NAME: mulesoft_traceability_agent
      ORG_NAME: Axway
      VERSION: ${{ github.ref_name }}
      COMMIT_ID: ${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: latest=false
          images: ghcr.io/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/traceability.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
