name: Go Build & Test
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
defaults:
  run:
    working-directory: ./mulesoft_discovery_agent

jobs:
  build:
    #if: contains(github.ref, 'mulesoft_discovery_agent')
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.0'
    - run: go mod download
    - name: Build & Test
      run: |
        go build -v .
        go test ./...
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@master
      with:
        workdir: ./mulesoft_discovery_agent
        args: release --snapshot --skip-publish --rm-dist
