name: Go Build & Test
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    #if: contains(github.ref, 'mulesoft_discovery_agent')
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.0'
    - run: go mod download

    - name: Discovery Build & Test
      working-directory: ./mulesoft_discovery_agent
      run: |
        go build -v .
        go test ./...

    - name: Traceability Build & Test
      working-directory: ./mulesoft_traceability_agent
      run: |
        go build -v .
        go test ./...

    - name: Discovery Release (Snapshot)
      uses: goreleaser/goreleaser-action@master
      with:
        workdir: ./mulesoft_discovery_agent
        args: release --snapshot --skip-publish --rm-dist

    - name: Traceability Release (Snapshot)
      uses: goreleaser/goreleaser-action@master
      with:
        workdir: ./mulesoft_traceability_agent
        args: release --snapshot --skip-publish --rm-dist
