name: Go Build & Test
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  build-discovery:
    runs-on: ubuntu-latest
    name: Build & Test
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.0'
    - run: make download
    - name: Discovery Build & Test
      run: |
        make build-discovery .
        go test ./...
    - name: Discovery Release (Snapshot)
      uses: goreleaser/goreleaser-action@master
      with:
        workdir: .
        args: release --snapshot --skip-publish --rm-dist

  build-traceability:
    runs-on: ubuntu-latest
    name: Build & Test
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.0'
    - run: make download
    - name: Traceability Build & Test
      run: |
        make build-trace
        go test ./...
    - name: Traceability Release (Snapshot)
      uses: goreleaser/goreleaser-action@master
      with:
        workdir: .
        args: release --snapshot --skip-publish --rm-dist
