name: Go Build & Test
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.2'
    - name: download
      run: make download
    - name: Discovery Build
      run: make build-discovery
    - name: Traceability Build
      run: make build-trace
    - name: Test Agents
      run : make test
    - name: Discovery Release (Snapshot)
      uses: goreleaser/goreleaser-action@v2.5.0
      with:
        workdir: ./cmd/discovery
        args: release --snapshot --skip-publish --rm-dist
    - name: Traceability Release (Snapshot)
      uses: goreleaser/goreleaser-action@v2.5.0
      with:
        workdir: ./cmd/traceability
        args: release --snapshot --skip-publish --rm-dist
