
name: Release with goreleaser
on:
  push:
    tags:
      - v*.*.*

jobs:
  discoveryw:
    runs-on: ubuntu-latest
    name: Release discoveryyyy
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow Fetchxxx
      run: git fetch --prune --unshallow
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.0'
    - name: Discovery Release
      uses: goreleaser/goreleaser-action@v2.5.0
      with:
        workdir: ./cmd/discovery
        args: release -f ../../.goreleaser.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  traceability5:
    runs-on: ubuntu-latest
    name: Release traceabilityzzzz
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow Fetchaaa
      run: git fetch --prune --unshallow
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.0'
    - name: Traceability Release
      uses: goreleaser/goreleaser-action@v2.5.0
      with:
        workdir: ./cmd/traceability
        args: release -f ../../.goreleaser-ta.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
