
name: Release agents with goreleaser
on:
  push:
    tags:
      - v*.*.*

jobs:
  discovery:
    runs-on: ubuntu-latest
    name: Release discovery
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow Fetch
      run: git fetch --prune --unshallow
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.0'
    - name: Get SDK version
      # run: echo "go list -m github.com/Axway/agent-sdk | awk '{print $$2}' | awk -F'-' '{print substr($$1, 2)}'" >> $GITHUB_SDKVER
      run: echo "SdkVersion=12345 >> $GITHUB_ENV
    - name: Discovery Release
      uses: goreleaser/goreleaser-action@v2.5.0
      with:
        args: release -f .goreleaser-da.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
  traceability:
    runs-on: ubuntu-latest
    name: Release traceability
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow Fetch
      run: git fetch --prune --unshallow
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.0'
    - name: Traceability Release
      uses: goreleaser/goreleaser-action@v2.5.0
      with:
        args: release -f .goreleaser-ta.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
